### ISSUE TITLE
Fix it

### ISSUE THREAD

**Issue by nopeynope69** [Temperz87/ultra-mod-manager#37] opened 2023-12-30 21:23 UTC
just fix it, i know you are online. I know you are active. just fix this **G O D D A M N** mod

**Comment by SnakeFins** [comment] 2023-12-30 21:50
dude calm down; the devs are more than likely working on fixing it now - these things take time

**Comment by Temperz87** [comment] 2024-01-01 10:22
No
Closed, duplicate of #34

**Closed as completed by Temperz87** 2024-01-01 10:22 UTC
