### ISSUE TITLE
Mods Tab Not Showing up in New Update

### ISSUE THREAD

**Issue by Ultrakillfan** [Temperz87/ultra-mod-manager#35] opened 2023-12-27 00:37 UTC
![image](https://github.com/Temperz87/ultra-mod-manager/assets/154939213/db8e7d82-681e-4931-a3c7-836c70b2edfb)

**Comment by Temperz87** [comment] 2023-12-29 22:07
Closed, duplicate of #34

**Closed as completed by Temperz87** 2023-12-29 22:07 UTC
