### ISSUE TITLE
Recent Update Broke This

### ISSUE THREAD

**Issue by CursedSFMS** [Temperz87/ultra-mod-manager#36] opened 2023-12-29 06:37 UTC
![download (12)](https://github.com/Temperz87/ultra-mod-manager/assets/103972920/1db7d2e0-2327-4ec6-82c6-4633cd321d6e)

**Comment by Temperz87** [comment] 2023-12-29 22:06
Closed, duplicate of #34

**Closed as completed by Temperz87** 2023-12-29 22:06 UTC
